### ISSUE TITLE
Weird bug upgrading from 0.2.0 to 1.1.0

### ISSUE THREAD

**Issue by frankzilla15** [clowne-rb/clowne#33]
Hello,

Thank you for your had work! This gem is awesome.

I'm having a hard time debugging an issue after upgrading from 0.2.0 to 1.1.0. I am using the ActiveRecord adaptor with my Rails application and Ruby version 2.6.2.

After updating to the newest version, I am able to successfully clone new objects in my database without any issues. However, records that existed in 0.2.0 land throw an `ActiveRecord::RecordInvalid` error when trying to clone them.

I've noticed that the older records do not create `Operation` records after being cloned which I think may be the reason why they get an error. Newly created records do not have this problem and work as described in the documentation. Just to be clear, the same cloner is being used in both instances. One record was created before we upgraded to version 1.1.0 and the other after.

Any ideas about what could be causing this issue? It seems weird to me that the records would be aware of what version of Clowne was being used when they were created. Let me know if you need any more information.

**Comment by palkan** [comment]
Hey, thanks for the feedback! and for the report as well)

ActiveRecord is not aware of Clowne, it doesn't leave any _trace_ in it.

Could you share a little bit more information? For example, a cloner class and the `ActiveRecord::RecordInvalid` details (which validations fail)

**Comment by ssnickolay** [comment]
Closed due to statute of limitations.
