### ISSUE TITLE
Migrate to Standard

### ISSUE THREAD

**Issue by palkan** [clowne-rb/clowne#36]
- Migrate to [Standard](https://github.com/testdouble/standard)
- Freeze its version to avoid [failing builds](https://travis-ci.org/palkan/clowne/builds/541037666) due to RuboCop upgrades

**Comment by ssnickolay** [comment]
@palkan do you use `Standard` in other gems? Why it is better than fixing new Rubocop offences?

**Comment by ssnickolay** [comment]
@palkan sold! I'll take care of this next weekend
