### ISSUE TITLE
Ruby 3.0 compatibility

### ISSUE THREAD

**Issue by pomartel** [clowne-rb/clowne#57]
It looks like Clowne is not compatible with Ruby 3.0. I get a lot of errors like these when running the tests suite:
```
ArgumentError: wrong number of arguments (given 2, expected 1)
```
This appears to be related to [this breaking change](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) in Ruby 3.0.

**Comment by ssnickolay** [comment]
Hi @pomartel! Ruby 3.0 was released not so long ago, and we didn't have time to support it. I think I'll look at this problem current or next week.
BTW we are open to PRs If you want to help with Ruby 3.0 compatibility ;)

**Comment by pomartel** [comment]
It was my original intention to see if I could submit a PR but this is all a bit too much black belt ruby for me! ;)

Anyways, I was just playing around with Ruby 3.0 and I'm in no rush to upgrade. Thanks for your support!

**Comment by aserafin** [comment]
@ssnickolay would you consider pushing new release with ruby3 support to rubygems? we're currently forced to refer to master

**Comment by ssnickolay** [comment]
@aserafin sorry for the delay, I've been a bit busy last few month; I'm going to release it this weekend

**Comment by ssnickolay** [comment]
The gem has been released: https://rubygems.org/gems/clowne/versions/1.3.0 🎉 
@pomartel thanks again for your work!
