### ISSUE TITLE
Release with mapper access in `after_clone`

### ISSUE THREAD

**Issue by dmkash** [clowne-rb/clowne#68]
It would be awesome if a new release could be cut that includes PR #60 in it. I've been using a fork with this branch merged in and it really fits our needs very well.  Thank you!!

**Comment by ssnickolay** [comment]
I'm so sorry folks, I prepared everything for release during Hacktoberfest but then somehow forgot about it

Here is the release: https://github.com/clowne-rb/clowne/releases/tag/v1.4.0
Also available on RubyGems: https://rubygems.org/gems/clowne/versions/1.4.0

**Comment by dmkash** [comment]
No worries!! Thank you so much! This gem has been such a huge help to me!!
