### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by simonoff** [clowne-rb/clowne#71]
Hello guys,

I see that you copied a lot of our logic from https://github.com/amoeba-rb/amoeba but not mentioned it.
I see one of mainteiners was a contributor in amoeba.

Can you add a mention on original library?

**Comment by palkan** [comment]
Hey,

We didn't copy any logic but our prior experience with amoeba has definitely inspired the API of this gem. And we mention this fact in the [docs](https://clowne.evilmartians.io/#/getting_started?id=motivation-amp-alternatives) and in the [intro blog post](https://evilmartians.com/chronicles/clowne-clone-ruby-models-with-a-smile).
